#!/usr/bin/env python3

#  Copyright (c) 2015 Shane Ambler
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are
#  met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following disclaimer
#    in the documentation and/or other materials provided with the
#    distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

from subprocess import call
from sys import argv
import os
import platform

sdir = os.path.abspath(os.path.dirname(argv[0]))

# for most users this should work, adjust if needed
if platform.system() == 'Darwin':
    blendapp = '/Applications/Blender/blender.app/Contents/MacOS/blender'
elif platform.system() == 'Windows':
    blendapp = 'C:/Program Files/Blender Foundation/Blender/blender.exe'
else:
    # if blender can be found from your $PATH this will work
    # if not you need to adjust this to suit.
    blendapp = 'blender'

calllist = [
        blendapp,
        '--factory-startup',
        os.path.join(sdir, 'blend_image_view.blend'),
        '--python',
        os.path.join(sdir, 'blend_open_image_file.py'),
        '--']

# add the args we get as filenames
calllist.extend(argv)

call(calllist)
